import = [ "~/.config/alacritty/themes/solarized_dark.toml" ]

[font]
    size= 13
    normal = { family = "JetBrains Mono", style = "Regular"}
    bold = { family = "JetBrains Mono", style = "Bold"}
    italic = { family = "JetBrains Mono", style = "Italic"}
    bold_italic = { family = "JetBrains Mono", style = "Bold Italic"}
[cursor]
# Estilo del cursor
style = { shape = "Block", blinking = "On" }

[scrolling]
history = 100000

# Configuración de selección
[selection]
save_to_clipboard = true
[window.padding]
x = 5
y = 5
